######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 18:21:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CommandProcessor.hpp Console.hpp OutputWindow.hpp
FORMS += Console.ui
SOURCES += CommandProcessor.cpp Console.cpp main.cpp OutputWindow.cpp
RESOURCES += Console.qrc
